#!/usr/bin/env node
// Script to add GlossaryGuard and CoverArchitect i18n keys to all language files

const fs = require('fs');
const path = require('path');

const messagesDir = path.join(__dirname, '../src/messages');

// New keys to add (with translations per language)
const translations = {
  GlossaryGuard: {
    en: { title: "Glossary Guard", termsProtected: "terms protected", addTerm: "Add Term Pair", source: "Source", target: "Target", sourceTermPlaceholder: "e.g., Warp Drive", targetTermPlaceholder: "e.g., Propulseur Vitesse", add: "Add", searchPlaceholder: "Search terms...", allCategories: "All Categories", noEntries: "No terms in your glossary yet.", noMatchingEntries: "No matching terms found.", addTermHint: "Add terms to ensure consistent translations throughout your book.", guardInfo: "Terms in this glossary will override AI translations and flag inconsistencies when you type a different translation.", addToGlossary: "Add to Glossary", added: "Added!", termExists: "Already in glossary", category: "Category", inconsistentTerm: "Inconsistent Term", found: "Found", shouldBe: "According to your glossary, this should be:", dismiss: "Dismiss", applyFix: "Apply Fix", fixed: "Fixed!" },
    fr: { title: "Garde Glossaire", termsProtected: "termes protégés", addTerm: "Ajouter une paire", source: "Source", target: "Cible", sourceTermPlaceholder: "ex. : Warp Drive", targetTermPlaceholder: "ex. : Propulseur Vitesse", add: "Ajouter", searchPlaceholder: "Rechercher...", allCategories: "Toutes les catégories", noEntries: "Aucun terme dans votre glossaire.", noMatchingEntries: "Aucun terme correspondant.", addTermHint: "Ajoutez des termes pour assurer des traductions cohérentes.", guardInfo: "Les termes de ce glossaire remplaceront les traductions IA et signaleront les incohérences.", addToGlossary: "Ajouter au glossaire", added: "Ajouté !", termExists: "Déjà dans le glossaire", category: "Catégorie", inconsistentTerm: "Terme incohérent", found: "Trouvé", shouldBe: "Selon votre glossaire, cela devrait être :", dismiss: "Ignorer", applyFix: "Appliquer", fixed: "Corrigé !" },
    de: { title: "Glossar-Wächter", termsProtected: "geschützte Begriffe", addTerm: "Begriff hinzufügen", source: "Quelle", target: "Ziel", sourceTermPlaceholder: "z.B. Warp Drive", targetTermPlaceholder: "z.B. Warp-Antrieb", add: "Hinzufügen", searchPlaceholder: "Suchen...", allCategories: "Alle Kategorien", noEntries: "Noch keine Begriffe im Glossar.", noMatchingEntries: "Keine passenden Begriffe.", addTermHint: "Fügen Sie Begriffe hinzu für konsistente Übersetzungen.", guardInfo: "Begriffe in diesem Glossar überschreiben KI-Übersetzungen.", addToGlossary: "Zum Glossar hinzufügen", added: "Hinzugefügt!", termExists: "Bereits im Glossar", category: "Kategorie", inconsistentTerm: "Inkonsistenter Begriff", found: "Gefunden", shouldBe: "Laut Glossar sollte dies sein:", dismiss: "Verwerfen", applyFix: "Korrigieren", fixed: "Korrigiert!" },
    es: { title: "Guardián del Glosario", termsProtected: "términos protegidos", addTerm: "Añadir par", source: "Origen", target: "Destino", sourceTermPlaceholder: "ej.: Warp Drive", targetTermPlaceholder: "ej.: Propulsor Warp", add: "Añadir", searchPlaceholder: "Buscar...", allCategories: "Todas las categorías", noEntries: "Aún no hay términos.", noMatchingEntries: "No se encontraron términos.", addTermHint: "Añade términos para traducciones consistentes.", guardInfo: "Los términos del glosario anularán las traducciones de IA.", addToGlossary: "Añadir al glosario", added: "¡Añadido!", termExists: "Ya está en el glosario", category: "Categoría", inconsistentTerm: "Término inconsistente", found: "Encontrado", shouldBe: "Según tu glosario, debería ser:", dismiss: "Descartar", applyFix: "Aplicar", fixed: "¡Corregido!" },
    it: { title: "Guardiano del Glossario", termsProtected: "termini protetti", addTerm: "Aggiungi coppia", source: "Origine", target: "Destinazione", sourceTermPlaceholder: "es.: Warp Drive", targetTermPlaceholder: "es.: Propulsore Warp", add: "Aggiungi", searchPlaceholder: "Cerca...", allCategories: "Tutte le categorie", noEntries: "Nessun termine nel glossario.", noMatchingEntries: "Nessun termine trovato.", addTermHint: "Aggiungi termini per traduzioni coerenti.", guardInfo: "I termini del glossario sovrascriveranno le traduzioni IA.", addToGlossary: "Aggiungi al glossario", added: "Aggiunto!", termExists: "Già nel glossario", category: "Categoria", inconsistentTerm: "Termine incoerente", found: "Trovato", shouldBe: "Secondo il glossario, dovrebbe essere:", dismiss: "Ignora", applyFix: "Applica", fixed: "Corretto!" },
    pt: { title: "Guardião do Glossário", termsProtected: "termos protegidos", addTerm: "Adicionar par", source: "Origem", target: "Destino", sourceTermPlaceholder: "ex.: Warp Drive", targetTermPlaceholder: "ex.: Propulsor Warp", add: "Adicionar", searchPlaceholder: "Pesquisar...", allCategories: "Todas as categorias", noEntries: "Nenhum termo no glossário.", noMatchingEntries: "Nenhum termo encontrado.", addTermHint: "Adicione termos para traduções consistentes.", guardInfo: "Os termos do glossário substituirão as traduções de IA.", addToGlossary: "Adicionar ao glossário", added: "Adicionado!", termExists: "Já está no glossário", category: "Categoria", inconsistentTerm: "Termo inconsistente", found: "Encontrado", shouldBe: "Segundo o glossário, deveria ser:", dismiss: "Ignorar", applyFix: "Aplicar", fixed: "Corrigido!" },
    ja: { title: "用語ガード", termsProtected: "保護された用語", addTerm: "用語ペアを追加", source: "原文", target: "訳文", sourceTermPlaceholder: "例：Warp Drive", targetTermPlaceholder: "例：ワープドライブ", add: "追加", searchPlaceholder: "検索...", allCategories: "すべてのカテゴリ", noEntries: "用語がありません。", noMatchingEntries: "一致する用語がありません。", addTermHint: "一貫した翻訳のために用語を追加してください。", guardInfo: "この用語集の用語はAI翻訳を上書きします。", addToGlossary: "用語集に追加", added: "追加しました！", termExists: "既に用語集にあります", category: "カテゴリ", inconsistentTerm: "不整合な用語", found: "検出", shouldBe: "用語集によると、これは次のようになるべきです：", dismiss: "無視", applyFix: "修正を適用", fixed: "修正しました！" },
    zh: { title: "术语守卫", termsProtected: "受保护的术语", addTerm: "添加术语对", source: "源语言", target: "目标语言", sourceTermPlaceholder: "例：Warp Drive", targetTermPlaceholder: "例：曲速引擎", add: "添加", searchPlaceholder: "搜索...", allCategories: "所有类别", noEntries: "术语表中还没有术语。", noMatchingEntries: "未找到匹配的术语。", addTermHint: "添加术语以确保翻译一致性。", guardInfo: "术语表中的术语将覆盖AI翻译。", addToGlossary: "添加到术语表", added: "已添加！", termExists: "已在术语表中", category: "类别", inconsistentTerm: "不一致的术语", found: "发现", shouldBe: "根据您的术语表，这应该是：", dismiss: "忽略", applyFix: "应用修复", fixed: "已修复！" },
    ko: { title: "용어 보호", termsProtected: "보호된 용어", addTerm: "용어 쌍 추가", source: "원문", target: "번역", sourceTermPlaceholder: "예: Warp Drive", targetTermPlaceholder: "예: 워프 드라이브", add: "추가", searchPlaceholder: "검색...", allCategories: "모든 카테고리", noEntries: "용어집에 용어가 없습니다.", noMatchingEntries: "일치하는 용어가 없습니다.", addTermHint: "일관된 번역을 위해 용어를 추가하세요.", guardInfo: "이 용어집의 용어가 AI 번역을 대체합니다.", addToGlossary: "용어집에 추가", added: "추가됨!", termExists: "이미 용어집에 있음", category: "카테고리", inconsistentTerm: "불일치 용어", found: "발견됨", shouldBe: "용어집에 따르면 다음과 같아야 합니다:", dismiss: "무시", applyFix: "수정 적용", fixed: "수정됨!" },
    ar: { title: "حارس المصطلحات", termsProtected: "مصطلحات محمية", addTerm: "إضافة زوج مصطلحات", source: "المصدر", target: "الهدف", sourceTermPlaceholder: "مثال: Warp Drive", targetTermPlaceholder: "مثال: محرك الانحناء", add: "إضافة", searchPlaceholder: "بحث...", allCategories: "جميع الفئات", noEntries: "لا توجد مصطلحات بعد.", noMatchingEntries: "لم يتم العثور على مصطلحات.", addTermHint: "أضف مصطلحات لترجمات متسقة.", guardInfo: "ستتجاوز مصطلحات القاموس ترجمات الذكاء الاصطناعي.", addToGlossary: "إضافة إلى القاموس", added: "تمت الإضافة!", termExists: "موجود بالفعل", category: "الفئة", inconsistentTerm: "مصطلح غير متسق", found: "وُجد", shouldBe: "وفقاً لقاموسك، يجب أن يكون:", dismiss: "تجاهل", applyFix: "تطبيق الإصلاح", fixed: "تم الإصلاح!" },
    ru: { title: "Страж глоссария", termsProtected: "защищённых терминов", addTerm: "Добавить пару", source: "Исходный", target: "Целевой", sourceTermPlaceholder: "напр.: Warp Drive", targetTermPlaceholder: "напр.: Варп-двигатель", add: "Добавить", searchPlaceholder: "Поиск...", allCategories: "Все категории", noEntries: "В глоссарии пока нет терминов.", noMatchingEntries: "Термины не найдены.", addTermHint: "Добавьте термины для согласованных переводов.", guardInfo: "Термины глоссария заменят переводы ИИ.", addToGlossary: "Добавить в глоссарий", added: "Добавлено!", termExists: "Уже в глоссарии", category: "Категория", inconsistentTerm: "Несогласованный термин", found: "Найдено", shouldBe: "Согласно глоссарию, должно быть:", dismiss: "Отклонить", applyFix: "Применить", fixed: "Исправлено!" }
  },
  CoverArchitect: {
    en: { title: "Cover Architect", kdpReady: "KDP Ready", needsAttention: "Needs Attention", configuration: "Configuration", trimSize: "Trim Size", paperStock: "Paper Stock", creamPaper: "Cream", whitePaper: "White", pageCount: "Page Count", syncFromProject: "Sync from project", barcode: "Barcode", includeBarcode: "Include barcode area", spineCalculator: "Live Spine Calculator", textAllowed: "Text Allowed", noTextOnSpine: "No Text on Spine", backCover: "BACK", frontCover: "FRONT", dimensions: "Final Dimensions", totalWidth: "Total Width", totalHeight: "Total Height", pixelWidth: "Pixel Width", pixelHeight: "Pixel Height", spineHiddenWarning: "Pages below {min} will have no visible spine on the cover.", minPagesError: "KDP requires at least 24 pages.", maxPagesError: "KDP allows a maximum of 828 pages.", downloadTemplate: "Download Cover Template", kdpNote: "This template follows Amazon KDP specifications. Use it as a guide when designing your cover in Photoshop, Canva, or any image editor." },
    fr: { title: "Architecte de Couverture", kdpReady: "Prêt pour KDP", needsAttention: "Attention requise", configuration: "Configuration", trimSize: "Format de coupe", paperStock: "Type de papier", creamPaper: "Crème", whitePaper: "Blanc", pageCount: "Nombre de pages", syncFromProject: "Synchroniser", barcode: "Code-barres", includeBarcode: "Inclure zone code-barres", spineCalculator: "Calculateur de dos", textAllowed: "Texte autorisé", noTextOnSpine: "Pas de texte sur le dos", backCover: "DOS", frontCover: "FACE", dimensions: "Dimensions finales", totalWidth: "Largeur totale", totalHeight: "Hauteur totale", pixelWidth: "Largeur en pixels", pixelHeight: "Hauteur en pixels", spineHiddenWarning: "Les livres de moins de {min} pages n'auront pas de dos visible.", minPagesError: "KDP exige au moins 24 pages.", maxPagesError: "KDP autorise maximum 828 pages.", downloadTemplate: "Télécharger le gabarit", kdpNote: "Ce gabarit suit les spécifications Amazon KDP." },
    de: { title: "Cover-Architekt", kdpReady: "KDP-bereit", needsAttention: "Aufmerksamkeit erforderlich", configuration: "Konfiguration", trimSize: "Schnittgröße", paperStock: "Papierart", creamPaper: "Creme", whitePaper: "Weiß", pageCount: "Seitenzahl", syncFromProject: "Synchronisieren", barcode: "Barcode", includeBarcode: "Barcode-Bereich einschließen", spineCalculator: "Buchrücken-Rechner", textAllowed: "Text erlaubt", noTextOnSpine: "Kein Text auf Buchrücken", backCover: "RÜCKSEITE", frontCover: "VORDERSEITE", dimensions: "Endmaße", totalWidth: "Gesamtbreite", totalHeight: "Gesamthöhe", pixelWidth: "Pixelbreite", pixelHeight: "Pixelhöhe", spineHiddenWarning: "Bücher unter {min} Seiten haben keinen sichtbaren Buchrücken.", minPagesError: "KDP erfordert mindestens 24 Seiten.", maxPagesError: "KDP erlaubt maximal 828 Seiten.", downloadTemplate: "Vorlage herunterladen", kdpNote: "Diese Vorlage folgt den Amazon KDP-Spezifikationen." },
    es: { title: "Arquitecto de Portada", kdpReady: "Listo para KDP", needsAttention: "Requiere atención", configuration: "Configuración", trimSize: "Tamaño de corte", paperStock: "Tipo de papel", creamPaper: "Crema", whitePaper: "Blanco", pageCount: "Número de páginas", syncFromProject: "Sincronizar", barcode: "Código de barras", includeBarcode: "Incluir área de código", spineCalculator: "Calculadora de lomo", textAllowed: "Texto permitido", noTextOnSpine: "Sin texto en lomo", backCover: "TRASERA", frontCover: "FRONTAL", dimensions: "Dimensiones finales", totalWidth: "Ancho total", totalHeight: "Alto total", pixelWidth: "Ancho en píxeles", pixelHeight: "Alto en píxeles", spineHiddenWarning: "Libros con menos de {min} páginas no tendrán lomo visible.", minPagesError: "KDP requiere al menos 24 páginas.", maxPagesError: "KDP permite máximo 828 páginas.", downloadTemplate: "Descargar plantilla", kdpNote: "Esta plantilla sigue las especificaciones de Amazon KDP." },
    it: { title: "Architetto Copertina", kdpReady: "Pronto per KDP", needsAttention: "Richiede attenzione", configuration: "Configurazione", trimSize: "Formato di taglio", paperStock: "Tipo di carta", creamPaper: "Crema", whitePaper: "Bianco", pageCount: "Numero di pagine", syncFromProject: "Sincronizza", barcode: "Codice a barre", includeBarcode: "Includi area codice", spineCalculator: "Calcolatore dorso", textAllowed: "Testo consentito", noTextOnSpine: "Nessun testo sul dorso", backCover: "RETRO", frontCover: "FRONTE", dimensions: "Dimensioni finali", totalWidth: "Larghezza totale", totalHeight: "Altezza totale", pixelWidth: "Larghezza in pixel", pixelHeight: "Altezza in pixel", spineHiddenWarning: "Libri con meno di {min} pagine non avranno dorso visibile.", minPagesError: "KDP richiede almeno 24 pagine.", maxPagesError: "KDP consente massimo 828 pagine.", downloadTemplate: "Scarica modello", kdpNote: "Questo modello segue le specifiche Amazon KDP." },
    pt: { title: "Arquiteto de Capa", kdpReady: "Pronto para KDP", needsAttention: "Requer atenção", configuration: "Configuração", trimSize: "Tamanho de corte", paperStock: "Tipo de papel", creamPaper: "Creme", whitePaper: "Branco", pageCount: "Número de páginas", syncFromProject: "Sincronizar", barcode: "Código de barras", includeBarcode: "Incluir área de código", spineCalculator: "Calculadora de lombada", textAllowed: "Texto permitido", noTextOnSpine: "Sem texto na lombada", backCover: "TRASEIRA", frontCover: "FRONTAL", dimensions: "Dimensões finais", totalWidth: "Largura total", totalHeight: "Altura total", pixelWidth: "Largura em pixels", pixelHeight: "Altura em pixels", spineHiddenWarning: "Livros com menos de {min} páginas não terão lombada visível.", minPagesError: "KDP exige pelo menos 24 páginas.", maxPagesError: "KDP permite no máximo 828 páginas.", downloadTemplate: "Baixar modelo", kdpNote: "Este modelo segue as especificações da Amazon KDP." },
    ja: { title: "カバーアーキテクト", kdpReady: "KDP対応", needsAttention: "注意が必要", configuration: "設定", trimSize: "トリムサイズ", paperStock: "紙の種類", creamPaper: "クリーム", whitePaper: "白", pageCount: "ページ数", syncFromProject: "同期", barcode: "バーコード", includeBarcode: "バーコードエリアを含む", spineCalculator: "背表紙計算機", textAllowed: "テキスト可", noTextOnSpine: "背表紙にテキスト不可", backCover: "裏表紙", frontCover: "表紙", dimensions: "最終寸法", totalWidth: "全幅", totalHeight: "全高", pixelWidth: "ピクセル幅", pixelHeight: "ピクセル高", spineHiddenWarning: "{min}ページ未満の本には背表紙がありません。", minPagesError: "KDPは最低24ページ必要です。", maxPagesError: "KDPは最大828ページまでです。", downloadTemplate: "テンプレートをダウンロード", kdpNote: "このテンプレートはAmazon KDPの仕様に従っています。" },
    zh: { title: "封面设计师", kdpReady: "KDP就绪", needsAttention: "需要注意", configuration: "配置", trimSize: "裁切尺寸", paperStock: "纸张类型", creamPaper: "奶油色", whitePaper: "白色", pageCount: "页数", syncFromProject: "同步", barcode: "条形码", includeBarcode: "包含条形码区域", spineCalculator: "书脊计算器", textAllowed: "允许文字", noTextOnSpine: "书脊无文字", backCover: "封底", frontCover: "封面", dimensions: "最终尺寸", totalWidth: "总宽度", totalHeight: "总高度", pixelWidth: "像素宽度", pixelHeight: "像素高度", spineHiddenWarning: "少于{min}页的书没有可见书脊。", minPagesError: "KDP要求至少24页。", maxPagesError: "KDP最多允许828页。", downloadTemplate: "下载模板", kdpNote: "此模板遵循亚马逊KDP规范。" },
    ko: { title: "커버 아키텍트", kdpReady: "KDP 준비됨", needsAttention: "주의 필요", configuration: "구성", trimSize: "트림 크기", paperStock: "용지 종류", creamPaper: "크림", whitePaper: "화이트", pageCount: "페이지 수", syncFromProject: "동기화", barcode: "바코드", includeBarcode: "바코드 영역 포함", spineCalculator: "책등 계산기", textAllowed: "텍스트 허용", noTextOnSpine: "책등에 텍스트 없음", backCover: "뒷표지", frontCover: "앞표지", dimensions: "최종 치수", totalWidth: "총 너비", totalHeight: "총 높이", pixelWidth: "픽셀 너비", pixelHeight: "픽셀 높이", spineHiddenWarning: "{min}페이지 미만의 책은 책등이 보이지 않습니다.", minPagesError: "KDP는 최소 24페이지가 필요합니다.", maxPagesError: "KDP는 최대 828페이지까지 허용합니다.", downloadTemplate: "템플릿 다운로드", kdpNote: "이 템플릿은 Amazon KDP 사양을 따릅니다." },
    ar: { title: "مهندس الغلاف", kdpReady: "جاهز لـ KDP", needsAttention: "يحتاج انتباه", configuration: "الإعدادات", trimSize: "حجم القطع", paperStock: "نوع الورق", creamPaper: "كريمي", whitePaper: "أبيض", pageCount: "عدد الصفحات", syncFromProject: "مزامنة", barcode: "الباركود", includeBarcode: "تضمين منطقة الباركود", spineCalculator: "حاسبة الكعب", textAllowed: "النص مسموح", noTextOnSpine: "لا نص على الكعب", backCover: "الخلفية", frontCover: "الأمامية", dimensions: "الأبعاد النهائية", totalWidth: "العرض الكلي", totalHeight: "الارتفاع الكلي", pixelWidth: "عرض البكسل", pixelHeight: "ارتفاع البكسل", spineHiddenWarning: "الكتب أقل من {min} صفحة لن يكون لها كعب مرئي.", minPagesError: "KDP يتطلب 24 صفحة على الأقل.", maxPagesError: "KDP يسمح بحد أقصى 828 صفحة.", downloadTemplate: "تحميل القالب", kdpNote: "هذا القالب يتبع مواصفات Amazon KDP." },
    ru: { title: "Архитектор обложки", kdpReady: "Готово для KDP", needsAttention: "Требует внимания", configuration: "Конфигурация", trimSize: "Размер обрезки", paperStock: "Тип бумаги", creamPaper: "Кремовая", whitePaper: "Белая", pageCount: "Количество страниц", syncFromProject: "Синхронизировать", barcode: "Штрих-код", includeBarcode: "Включить область штрих-кода", spineCalculator: "Калькулятор корешка", textAllowed: "Текст разрешён", noTextOnSpine: "Без текста на корешке", backCover: "ЗАДНЯЯ", frontCover: "ПЕРЕДНЯЯ", dimensions: "Итоговые размеры", totalWidth: "Общая ширина", totalHeight: "Общая высота", pixelWidth: "Ширина в пикселях", pixelHeight: "Высота в пикселях", spineHiddenWarning: "Книги менее {min} страниц не будут иметь видимого корешка.", minPagesError: "KDP требует минимум 24 страницы.", maxPagesError: "KDP допускает максимум 828 страниц.", downloadTemplate: "Скачать шаблон", kdpNote: "Этот шаблон соответствует спецификациям Amazon KDP." }
  }
};

// Language file mappings to template language
const langMap = {
  'en': 'en', 'fr': 'fr', 'de': 'de', 'es': 'es', 'it': 'it', 'pt': 'pt',
  'ja': 'ja', 'zh': 'zh', 'zh-TW': 'zh', 'ko': 'ko', 'ar': 'ar', 'ru': 'ru',
  'nl': 'de', 'sv': 'de', 'no': 'de', 'da': 'de', 'fi': 'de',
  'pl': 'ru', 'cs': 'de', 'hu': 'de', 'ro': 'it', 'uk': 'ru',
  'el': 'en', 'he': 'en', 'hi': 'en', 'th': 'en', 'vi': 'en', 'id': 'en',
  'tr': 'en', 'fa': 'ar', 'ca': 'es', 'la': 'it', 'grc': 'en'
};

// Process each language file
const files = fs.readdirSync(messagesDir).filter(f => f.endsWith('.json'));
let updated = 0;

for (const file of files) {
  const lang = file.replace('.json', '');
  const filePath = path.join(messagesDir, file);
  
  try {
    const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    const templateLang = langMap[lang] || 'en';
    
    // Add GlossaryGuard if missing or incomplete
    if (!content.GlossaryGuard || Object.keys(content.GlossaryGuard).length < 24) {
      content.GlossaryGuard = translations.GlossaryGuard[templateLang] || translations.GlossaryGuard.en;
    }
    
    // Add CoverArchitect if missing or incomplete
    if (!content.CoverArchitect || Object.keys(content.CoverArchitect).length < 25) {
      content.CoverArchitect = translations.CoverArchitect[templateLang] || translations.CoverArchitect.en;
    }
    
    fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
    updated++;
    console.log(`✓ Updated ${file}`);
  } catch (err) {
    console.error(`✗ Error processing ${file}:`, err.message);
  }
}

console.log(`\nDone! Updated ${updated}/${files.length} files.`);
